server:
  port: 8080
  address: 0.0.0.0

#OffHoursPushDetector
offHours:
  start:
    hour: 0
    minute: 0
  end:
    hour: 2
    minute: 0

# RapidRepoLifecycleDetector
repositoryMinLifetimeMinutes: 10

# InvalidTeamNameDetector
invalidTeamNamePrefix: hacker
